apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.0.7
    chart: nginx-ingress-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-argo
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
